# CSE x25 Lab 1
TOP_MODULE = counter
SYNTH_SOURCES += $(TOP_MODULE).sv
SYNTH_SOURCES += ../../part1/adder/adder.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk

