TOP_MODULE = graycounter
SYNTH_SOURCES += $(TOP_MODULE).sv
SYNTH_SOURCES += ../../part1/bintogray/bintogray.sv
SYNTH_SOURCES += ../../part1/graytobin/graytobin.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk

