TOP_MODULE += ycbcr
SYNTH_SOURCES += $(TOP_MODULE).sv
SYNTH_SOURCES += ../../provided_modules/elastic_pipe.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk
