TOP_MODULE += filter
SYNTH_SOURCES += $(TOP_MODULE).sv
SYNTH_SOURCES += ../../part3/filter/shift.sv
SYNTH_SOURCES += ../../provided_modules/axis_i2s2.v
SYNTH_SOURCES += ../../provided_modules/inv.sv
SYNTH_SOURCES += ../../provided_modules/dff.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk
-include ../../fpga.mk

