TOP_MODULE = ram_1r1w_async
SYNTH_SOURCES += $(TOP_MODULE).sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk
-include ../../sby.mk

