# CSE x25 Lab 1
#TOP_MODULE = graycounter
#SYNTH_SOURCES += $(TOP_MODULE).sv
#SYNTH_SOURCES += ../../part1/graycounter/graycounter_nobug.sv
#SYNTH_SOURCES += ../../part1/graycounter/graycounter_bug1.sv
#SYNTH_SOURCES += ../../part1/graycounter/graycounter_bug2b.sv
SYNTH_SOURCES += ../../part1/graycounter/graycounter.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk

