# CSE x25 Lab 1
TOP_MODULE = ram_1w1r_async
SYNTH_SOURCES += $(TOP_MODULE).sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk
-include ../../fpga.mk

