# CSE x25 Lab 2
TOP_MODULE += elastic_pipe
SYNTH_SOURCES += $(TOP_MODULE).sv
SYNTH_SOURCES += ../../provided_modules/dff.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk
