# CSE x25 Lab 2
TOP_MODULE = xor2
SYNTH_SOURCES += $(TOP_MODULE).sv
SYNTH_SOURCES += ../../provided_modules/LUT6.v
SYNTH_SOURCES += ../../provided_modules/LUT6_2.v
-include ../../simulation.mk
-include ../../fpga.mk

