# CSE x25 Lab 1
TOP_MODULE = lfsr
SYNTH_SOURCES += $(TOP_MODULE).sv
SYNTH_SOURCES += ../shift/shift.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_clock_gen.sv
NONSYNTH_SOURCES += ../../provided_modules/nonsynth_reset_gen.sv
-include ../../simulation.mk
-include ../../fpga.mk
